server:
  port: 8383
spring:
  application:
    name: POSITION-SERVICE
  data:
    mongodb:
      database: Flotte
      host: localhost
      port: 27017


eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ # url de Eureka Server
