eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
server:
  port: 8383
spring:
  application:
    name: POSITION-SERVICE
  data:
    mongodb:
      database: POSITION_FLOTTE
      host: localhost
      port : 27017


    zipkin:
      base-url: http://localhost:9411
      sender:
        type: web

    sleuth:
      sample:
        probability: 1


corsConfiguration:
  Origins: http://localhost:4200

keycloak:
  realm: flotte-realm
  resource: flotte-client
  bearer-only: true
  auth-server-url: http://localhost:9090/
  ssl-required: none
