eureka:
#    client:
#        serviceUrl:
#            defaultZone: http://localhost:8761/eureka/
    instance:
        instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
server:
    port: ${PORT:0}
spring:
    application:
        name: user-ws
#    data:
#        mongodb:
#            database: Flotte
#            host: 192.168.251.4
#            port: 27017
#    devtools:
#        restart:
#            enabled: true
#    sleuth:
#        sampler:
#            probability: 1
#    zipkin:
#        base-url: http://localhost:9411
#        sender:
#            type: web
#token:
#    expiration_time: 8640000
#    seecret: absdefijklmn12nmlkjifessm

