server:
    port: 8282
spring:
    application:
        name: DEVICE-SERVICE
keycloak:
    realm: flotte-realm
    resource: flotte-client
    bearer-only: true
    auth-server-url: http://localhost:9090
    ssl-required: none

